name: biobb_MDsetup_tutorial
channels:
  - conda-forge
  - bioconda
dependencies:
  - biobb_common==3.0.0
  - biobb_analysis==3.0.1
  - biobb_io==3.0.0
  - biobb_model==3.0.0
  - biobb_md==3.0.0
  - nb_conda_kernels
  - plotly
  - nglview
  - simpletraj
  - conda